### ISSUE TITLE
rasa 1.2.3 can not using rasa-sdk 1.3.0a1

### ISSUE THREAD

**Issue by sackaboy** [RasaHQ/rasa-sdk#101]
**Python version:**
3.6
**Operating system (windows, osx, ...):**
linux

when I install rasa, it reports an error:
rasa 1.2.3 has requirement rasa-sdk~=1.1.0, but you'll have rasa-sdk 1.3.0a1 which is incompatible.

I tried reinstalling rasa-sdk 1.1.0, but when I reinstalled rasa,The same error occurred again (rasa automatically installed rasa-sdk1.3.0a1).

**Comment by akelad** [comment]
@erohmensing we pinned this properly recently didn't we?

**Comment by erohmensing** [comment]
it got pinned correctly as of 1.2.4.

> when I reinstalled rasa,The same error occurred again (rasa automatically installed rasa-sdk1.3.0a1)

@sackaboy are you installing with pip install or from github? If the former, not sure why it would install `rasa-sdk==1.3.0a1`. It should get you `rasa==1.2.4` and `rasa-sdk==1.2.0`.

**Comment by sackaboy** [comment]
@erohmensing thanks you so much
