### ISSUE TITLE
Form(None) not working in custom reset action

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#104]
**Rasa version**: 1.2.5

**Rasa SDK version**: 1.2.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu (with WSL)

**Issue**: 
I have created a custom action to fully reset the conversation, slots, and deactivate any form that could still be running (the reason being that the standard `action_restart` did not deactivate forms). 

My action basically does: `[Form(None), AllSlotsReset(None), Restarted(None)]` (full code below).

The action is triggered by a mapped intent called `reset`. Typing `Reset` should trigger this action. 

This usually works fine but we've had cases where the bot is just stuck in a form. It usually happens when we do not talk to the bot for a while and try to reset the conversation (but not always). It is quite erratic and the only solution we found was to delete the whole tracker for this conversation (directly in the DB). 

Not sure if this is a bug with the `rasa_sdk` or if my custom action is wrong. 

Thanks for your help!

**Error (including full traceback)**:
No error

**Command or request that led to error**:
- Start a form 
- Type "Reset" (identified as intent `reset`)
- Type "Hi" (bot should start the conversation from the beginning)

**Content of domain file (domain.yml)** (if relevant):
```yml
actions:
...
- action_reset_full

intents:
...
- reset:
    name: reset
    triggers: action_reset_full
```

**Contents of config file (if relevant)**:
```
policies:
  - name: MappingPolicy
  - ...
```

**Contents of actions.py** (if  relevant):
```python
# actions/reset_full.py
from rasa_sdk import Action
from rasa_sdk.events import Form, AllSlotsReset, Restarted


class ActionResetFull(Action):
    def name(self):
        return "action_reset_full"

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_template("utter_reset_full", tracker)
        return [Form(None), AllSlotsReset(None), Restarted(None)]
```

**Comment by akelad** [comment]
@nbeuchat do you have any logs from when it doesn't work?
