### ISSUE TITLE
TypeError: 'FollowupAction' object is not subscriptable

### ISSUE THREAD

**Issue by azizullah2017** [RasaHQ/rasa-sdk#120]
example:
bot: how can i help you?
user: yes
bot: sure, how can help you?

```
def validate()...:

		for slot, value in slot_values.items():
			elif slot == 'help':
				if value=='yes':
					dispatcher.utter_message('Sure, how may i help you?')
					return [SlotSet(slot, None),FollowupAction("action_listen")]
		return [SlotSet(slot, value) for slot, value in slot_values.items()]
```
Error
```
   if e["event"] == "slot":
if e["event"] == "slot":
TypeError: 'FollowupAction' object is not subscriptable
````

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @azizullah2017 , to better help you, it would be great if you could provide more details on this error. Where and when does it occur, and on what Rasa version? It would be helpful if you could share exact steps to reproduce this. In addition, would you mind correctly indenting the code you posted? Thanks a lot!

**Comment by azizullah2017** [comment]
rasa_sdk == 1.5.0
Rasa 1.5.0a1


@ricwo I am trying to reset the slot and forcing to listen.

without forcing to listen the bot behaves below.
```
for slot, value in slot_values.items():
			elif slot == 'help':
				if value=='yes':
					dispatcher.utter_message('Sure, how may i help you?')
					slot =  None
		return [SlotSet(slot, value) for slot, value in slot_values.items()]
```
example:
bot: how can i help you?
user: yes
bot: sure, how can help you?
bot: how can i help you?

I want this.
```
for slot, value in slot_values.items():
			elif slot == 'help':
				if value=='yes':
					dispatcher.utter_message('Sure, how may i help you?')
					return [SlotSet(slot, None),FollowupAction("action_listen")]
		return [SlotSet(slot, value) for slot, value in slot_values.items()]
```
example:
bot: how can i help you?
user: yes
bot: sure, how can help you? # in this step i want to reset the slot help and force to listen for user.
action_listen()

**Comment by ricwo** [comment]
@azizullah2017 , thanks - I still don't follow your code snippet. would you posting the full code snippet in a way that's runnable? A full and reproducible example would be great, thanks!

**Comment by azizullah2017** [comment]
Example 1: 
User: I want to book a room in PC hotel
Bot: sure, may I know about your arrival ?
User: I will reach ther at tomorrow at 5pm
Bot: Is there anything i can help you?
User: no
Bot: thanks

Example 2: 
User: I want to book a room in PC hotel
Bot: sure, may I know about your arrival ?
User: I will reach ther at tomorrow at 5pm
Bot: Is there anything i can help you?
User: yes
Bot:  Sure, how may i help you?'
```
	@staticmethod
	def required_slots(tracker: Tracker) -> List[Text]:
		return ["HotelName","arivalTime","help"]
		
	def validate(self,
				 dispatcher: CollectingDispatcher,
				 tracker: Tracker,
				 domain: Dict[Text, Any]) -> List[Dict]:
		slot_values = self.extract_other_slots(dispatcher, tracker, domain)
		slot_to_fill = tracker.get_slot(REQUESTED_SLOT)
		if slot_to_fill:
			slot_values.update(self.extract_requested_slot(dispatcher,
														   tracker, domain))
			if not slot_values:
				raise ActionExecutionRejection(self.name(),
											   "Failed to validate slot {0} "
											   "with action {1}"
											   "".format(slot_to_fill,
														 self.name()))

		for slot, value in slot_values.items():
			if slot == 'HotelName':
				if value =='yes':
					slot_values[slot] = None
			elif slot == 'help':
				if value=='yes':
					dispatcher.utter_message('Sure, how may i help you?')
					return [SlotSet(slot, None),FollowupAction("action_listen")]
				else:
					dispatcher.utter_template("utter_closing", tracker)
		return [SlotSet(slot, value) for slot, value in slot_values.items()]
```

**Comment by ricwo** [comment]
@azizullah2017, the import of `FollowupAction` should be from `rasa_sdk`, i.e.

```python
from rasa_sdk.events import FollowupAction
```

**Comment by azizullah2017** [comment]
@ricwo thanks. I do not get any error but it is action_listen is not working. 
Example 2:
```
User: I want to book a room in PC hotel
Bot: sure, may I know about your arrival ?
User: I will reach ther at tomorrow at 5pm
Bot: Is there anything i can help you?
User: yes
Bot: Sure, how may i help you?
## i want the bot to listen in here.
Bot: Is there anything i can help you?
## but it listens in here.
```

**Comment by ricwo** [comment]
Triggering a follow-up action should happen in a custom action's `run()` method, not in a form action's `validate()` method (this is for slot validation). please check out the docs on custom actions in python: https://rasa.com/docs/rasa/core/actions/#custom-actions-written-in-python

**Comment by ricwo** [comment]
Github issues are for bugs and feature requests. Please ask general usage questions in the forum: https://forum.rasa.com/
