### ISSUE TITLE
Unable to use async code in forms 

### ISSUE THREAD

**Issue by TheEnbyperor** [RasaHQ/rasa-sdk#134]
**Rasa version**: 1.6.0

**Rasa SDK version**: 1.6.0

**Python version**: 3.8

**Operating system** (windows, osx, ...): Nixos 19

**Issue**: Unable to use async code in forms. Rasa SDK executor is now async which means that the code in forms is run async however form functions are not able to be defined as async therefore await cannot be used in them. This causes problems with the likes of the Django ORM which forbids access in an async context without an await.

**Comment by erohmensing** [comment]
@TheEnbyperor thanks for pointing out this bug. I think form actions should indeed be defined as async (the knowledge base action too). I think the PR that moved everything to Sanic updated the executor but missed the other actions defined. Would you be able to contribute a PR to `rasa-sdk` to fix this?

**Comment by TheEnbyperor** [comment]
I've now done that in #135

**Comment by federicotdn** [comment]
Closed in https://github.com/RasaHQ/rasa-sdk/pull/142
