### ISSUE TITLE
actions.py not showing any output

### ISSUE THREAD

**Issue by sarthak-sriw** [RasaHQ/rasa-sdk#136]
when server starts and actions.py is being run , actions.py does not show desired output--

![Screenshot (71)](https://user-images.githubusercontent.com/53507883/71556383-035de900-2a5e-11ea-90a3-2959c787be97.png)

and server is showing following warning but when i try to update rasa to latest version cit shows following error:
![Screenshot (69)](https://user-images.githubusercontent.com/53507883/71556400-415b0d00-2a5e-11ea-944f-cd5b72385c79.png)

**Comment by rgstephens** [comment]
Github issues are for bugs and feature requests. Please ask general usage questions in the forum: https://forum.rasa.com/

The screenshot with your actions.py is cutoff but it looks like there are errors. Please continue this discussion on the forum.
