### ISSUE TITLE
Docker images shouldn't run as root

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-sdk#141]
Same as our `rasa` and `rasa-x` images, the sdk image should not run as root user.
To fix this, we can build upon the work from https://github.com/RasaHQ/rasa-sdk/pull/115 . Among the things which have to be wrapped up

- [ ] use group id `0`
- [ ] make sure all used folders are accessible for this group `0` (we have to make it accessible to the group and not to the user, since OpenShift runs with a random user but with a fixed group id `0`)

**Comment by alwx** [comment]
Also we need to check this issue after we actually manage to run all the images as non-root:
https://github.com/RasaHQ/rasa-x-helm/pull/18

**Comment by alwx** [comment]
Linked issues: https://github.com/RasaHQ/rasa-sdk/pull/145 & https://github.com/RasaHQ/rasa/pull/5223

(new Dockerfiles there use user 1001)
