### ISSUE TITLE
Allow multiple FollowupActions

### ISSUE THREAD

**Issue by tiz-lab** [RasaHQ/rasa-sdk#151]
**Description of Problem**:
At the moment it seems that only one FollowupAction is allowed to be called from a custom action. 

**Overview of the Solution**:
It would be useful if also a list of FollowupActions can be called from a custom action.

**Examples** (if relevant):
return [FollowupAction("action_1"), FollowupAction("action_2")]

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rgstephens will get back to you about it soon!✨

**Comment by akelad** [comment]
Hey @tiz-lab could you explain why you would need this feature? We generally don't recommend using `FollowupAction`s. Instead you should handle anything that comes after an action through stories.

**Comment by tiz-lab** [comment]
Hi @akelad, so my situation is the following:

1. the user sends a message with an intent that triggers a custom action
2. the action evaluates the value of a slot
3. if it's a certain value it returns an utterance
4. otherwise, it triggers 2 custom actions

In general, I don't think that calling actions from another action is an uncommon situation

**Comment by akelad** [comment]
But is there any reason why you wouldn't just do this with a story?

Calling a follow up action from an action makes it harder to see from the stories what is going on. And if no story like that exists then the model will also not know what to predict next

**Comment by tiz-lab** [comment]
How do I handle with stories the evaluation of a slot value? Or it could also be more complicated like, an API call and depending on the result I decide if returning an utterance or 2 actions.

**Comment by akelad** [comment]
@tiz-lab please ask usage questions on the [forum](https://forum.rasa.com)

You can use a custom action to set a slot, and then based on that slot value you can decide what to do in your stories. More info here:
https://rasa.com/docs/rasa/core/slots/
https://rasa.com/docs/rasa/user-guide/building-assistants/#more-complex-contextual-conversations

**Comment by tiz-lab** [comment]
This answers to my first question, but not the second one. If my evaluation is based on an API call, I need to use a custom action.
