### ISSUE TITLE
Requests library module not found with latest version of rasa-sdk image

### ISSUE THREAD

**Issue by karen-white** [RasaHQ/rasa-sdk#153]
**Rasa version**:
1.7.0
**Rasa SDK version**:
1.8.0
**Python version**:
3.6.9
**Operating system** (windows, osx, ...):
OSX
**Issue**:
Running custom action server code that imports the requests library throws an error when using the latest version of the rasa-sdk image. The module is found if you use the 1.7.0 version of the sdk image

Steps to reproduce:
- Deploy assistant to a server using docker-compose
- Create actions directory containing /actions.py and __init__.py
- Add actions code to action.py file that imports requests library
- Create docker-compose.override.yml file with the following:
```
version: '3.4'
services:
  app:
    image: 'rasa/rasa-sdk:latest'
    volumes:
      - './actions:/app/actions'
    expose:
      - '5005'
    depends_on:
      - rasa-production
```

Expected behavior:
Image should include the requests library

Actual behavior:
Returns error saying requests module is missing

Workaround:
Use custom action server image or rasa-sdk version 1.7

**Error (including full traceback)**:
```
Traceback (most recent call last):
app_1              |   File "/app/rasa_sdk/executor.py", line 206, in register_package
app_1              |     self._import_submodules(package)
app_1              |   File "/app/rasa_sdk/executor.py", line 191, in _import_submodules
app_1              |     package = importlib.import_module(package)
app_1              |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
app_1              |     return _bootstrap._gcd_import(name[level:], package, level)
app_1              |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
app_1              |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
app_1              |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
app_1              |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
app_1              |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
app_1              |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1              |   File "/app/actions/actions.py", line 6, in <module>
app_1              |     import requests
app_1              | ModuleNotFoundError: No module named 'requests'
```

**Command or request that led to error**:
Starting container after adding action server image

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
https://github.com/RasaHQ/medicare-assistant/blob/master/actions.py
cc @alwx

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Strange. It does seem to appear [here](https://github.com/RasaHQ/rasa-sdk/blob/15bc96d2ed89725ce7a295abeffacd02ae9e86f2/poetry.lock#L184).

**Comment by karen-white** [comment]
Yes, it's odd. Are you able to replicate the issue?

**Comment by Kamile-codes** [comment]
@karen-white I am not sure how this landed in Rasa Operations - should we put this issue somewhere else so it does not get lost? :)

**Comment by akelad** [comment]
@alwx any ideas on this?

**Comment by amn41** [comment]
just experienced this with carbon bot as well, reverting to docker tag 1.7.0 is a workaround for now

**Comment by alwx** [comment]
Sorry, I was not receiving any notifications for `rasa-sdk`, but it's fixed now so I should react faster next time :)
Will fix this issue today.

**Comment by Najko1** [comment]
Hi all,
sorry to write in an old ticket but I'm facing to the issue now.
Below you can see the error: 
![image](https://user-images.githubusercontent.com/17157351/106121582-01ca8d00-6158-11eb-8049-491bd5259758.png)
Here the installation satisfaction:
![image](https://user-images.githubusercontent.com/17157351/106121790-3b02fd00-6158-11eb-9c6e-834a4a5b854a.png)

My dockerfiles: 
![image](https://user-images.githubusercontent.com/17157351/106122293-d72d0400-6158-11eb-84fc-04222f37362c.png)

![image](https://user-images.githubusercontent.com/17157351/106122268-cda39c00-6158-11eb-90cd-0f735ebfe56b.png)



NOTE: 
My endpoint of action server is http://action_server:5055/webhook" because http://localhost:5055/webhook doesn't work

Thanks in advance
