### ISSUE TITLE
DOCKER: Outdated Dockerfile custom dependencies documentation

### ISSUE THREAD

**Issue by kremio** [RasaHQ/rasa-sdk#157]
**Rasa version**:
1.8.0
**Rasa SDK version**:
1.8.0
**Python version**:
not relevant
**Operating system** (windows, osx, ...):
not relevant
**Issue**:
With the current Docker image of RASA SDK, installing custom Python dependencies using the instructions provided on https://hub.docker.com/r/rasa/rasa-sdk does not work.
For instance, building the following Dockerfile:
```
FROM rasa/rasa-sdk:1.8.0
RUN pip --no-cache-dir install python-dateutil
```

results in the following *pip* error:
```
Collecting python-dateutil
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting six>=1.5
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, python-dateutil
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/venv/lib/python3.6/site-packages/six.py'
Consider using the `--user` option or check the permissions.
```
The reason is that the RASA SDK Dockerfile switches the build environment to a user with insufficient privileges:
https://github.com/RasaHQ/rasa-sdk/blob/a048b2b3014b58b5fa198333fe55754a865f6ce9/Dockerfile#L31
One possible solution is to sandwich the `RUN pip` commands between `USER root` and `USER 1001`, so the previous broken Dockerfile becomes:
```
FROM rasa/rasa-sdk:1.8.0
USER root
RUN pip --no-cache-dir install python-dateutil
USER 1001
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@kremio Since version 1.8.0 the image does not longer run as `root` user (following Docker best practices). In order to install your dependencies you have to switch to the `root` user before installing the dependencies.

```
FROM rasa/rasa-sdk:1.8.0
# Switch to root to install dependencies
USER ROOT
RUN pip --no-cache-dir install python-dateutil

# Switch back to non-root user
USER 1001
```

**Comment by wochinge** [comment]
I'll also clarify that in the docs! :-)

**Comment by ankitbansal811** [comment]
in the `USER ROOT` step root is case sensitive. Please use `USER root`
```
FROM rasa/rasa-sdk:1.8.0
# Switch to root to install dependencies
USER **root**
RUN pip --no-cache-dir install python-dateutil

# Switch back to non-root user
USER 1001`
```

**Comment by wochinge** [comment]
Thanks @ankitbansal811 🚀 Too many CAPS 😄
