### ISSUE TITLE
Add entity extractor parameter to slot mapping

### ISSUE THREAD

**Issue by JulianGerhard21** [RasaHQ/rasa-sdk#159]
**Description of Problem**:

Currently, if I want to fill a slot with an entity, I need to specify this the following way:

```
    def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
        return {
            "time": [
                self.from_entity(entity="time")
            ]
        }
```
Now let's say there is more than one EntityExtractor capable of extracting the same entity - e.g. "time" from DucklingHTTPExtractor which I want to use in Form A and self trained special situations extracted with DIET which I want to use in Form B. Now the parsing result for every user utterance would contain every occurence of the entity "time" regardless of the extractor and the slot_mapping might not pick the Form-relevant one.

**Overview of the Solution**:

I would suggest to be able to provide the favored extractor as a simple parameter to the mapping like this:
```
    def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
        return {
            "time": [
                self.from_entity(entity="time", extractor="DucklingHTTPExtractor")
            ]
        }
```
or this:
```
    def slot_mappings(self) -> Dict[Text, Union[Dict, List[Dict]]]:
        return {
            "time": [
                self.from_entity(entity="time", extractor="DucklingHTTPExtractor")
                self.from_entity(entity="time", extractor="SpacyEntityExtractor")
            ]
        }
```
such that I do not need to post-process the trackers entities if the wrong entity has been picked. As far as I have seen, we could provide this parameter to:
```
    @staticmethod
    def get_entity_value(name: Text, tracker: "Tracker") -> Any:
        """Extract entities for given name"""

        # list is used to cover the case of list slot type
        value = list(tracker.get_latest_entity_values(name))
        if len(value) == 0:
            value = None
        elif len(value) == 1:
            value = value[0]
        return value
```
which simply would have to be modified for this feature. The result would give as a bit more flexibility and at least slightly tackles to problem of "just picking the first given value". We would also need to modify:
```
    def from_entity(
        self,
        entity: Text,
        intent: Optional[Union[Text, List[Text]]] = None,
        not_intent: Optional[Union[Text, List[Text]]] = None,
    ) -> Dict[Text, Any]:
        """A dictionary for slot mapping to extract slot value.

        From:
        - an extracted entity
        - conditioned on
            - intent if it is not None
            - not_intent if it is not None,
                meaning user intent should not be this intent
        """

        intent, not_intent = self._list_intents(intent, not_intent)

        return {
            "type": "from_entity",
            "entity": entity,
            "intent": intent,
            "not_intent": not_intent,
        }
```

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature is documented
- [ ] Feature is implemented

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hey @JulianGerhard21 thanks for the suggestion - can I ask why you would have two entities from different entity extractors with the same name?
