### ISSUE TITLE
Add --log-file option when using the action server

### ISSUE THREAD

**Issue by roniemartinez** [RasaHQ/rasa-sdk#161]
**Description of Problem**:
There is no option to save logs to a log file when using the actions server from the command line as oppose to API server with `--log-file` argument

```
% rasa run actions --help
usage: rasa run actions [-h] [-v] [-vv] [--quiet] [-p PORT]
                        [--cors [CORS [CORS ...]]] [--actions ACTIONS]
                        [--ssl-keyfile SSL_KEYFILE]
                        [--ssl-certificate SSL_CERTIFICATE]
                        [--ssl-password SSL_PASSWORD]

optional arguments:
  -h, --help            show this help message and exit
  -p PORT, --port PORT  port to run the server at (default: 5055)
  --cors [CORS [CORS ...]]
                        enable CORS for the passed origin. Use * to whitelist
                        all origins (default: None)
  --actions ACTIONS     name of action package to be loaded (default: None)
  --ssl-keyfile SSL_KEYFILE
                        Set the SSL certificate to create a TLS secured
                        server. (default: None)
  --ssl-certificate SSL_CERTIFICATE
                        Set the SSL certificate to create a TLS secured
                        server. (default: None)
  --ssl-password SSL_PASSWORD
                        If your ssl-keyfile is protected by a password, you
                        can specify it using this paramer. (default: None)

Python Logging Options:
  -v, --verbose         Be verbose. Sets logging level to INFO. (default:
                        None)
  -vv, --debug          Print lots of debugging statements. Sets logging level
                        to DEBUG. (default: None)
  --quiet               Be quiet! Sets logging level to WARNING. (default:
                        None)
```

**Overview of the Solution**:
Add option for the action server to save logs to a log file similar to what the API server can do.

**Definition of Done**:
- [ ] Can pass `--log-file` as command line parameter

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi @roniemartinez, i think this sounds like a promising enhancement. However one thing to think about is that when the SDK is running as an image, it runs via the `start` command https://github.com/RasaHQ/rasa-sdk/blob/master/Dockerfile#L40
so i guess that parameter would need to be available for both methods

**Comment by roniemartinez** [comment]
> Sorry, can you get the logs from the API server? I'm not aware of that option.

@erohmensing  I misread it as you incorrectly added it to the quotes. It is actually the action server that does not have an option to save logs to a file. The logs can only be seen in the command line.

As for the API server, you can simply do this:
```
rasa run --log-file rasa.log --enable-api
```

For the action server, this does not work since the `--log-file` option does not belong to the subparser. And the subparser does not have this option as you can see from my [above description](https://github.com/RasaHQ/rasa-sdk/issues/161#issue-589132894).
```
rasa run --log-file rasa.log actions
```

**Comment by erohmensing** [comment]
Ah I see what you mean, the Rasa server, not the API of the Action Server. 

Would you like to work on adding this feature?

**Comment by roniemartinez** [comment]
> Would you like to work on adding this feature?

We'll see. Though, I certainly have not enough time right now.

**Comment by erohmensing** [comment]
Okay, I will open it up for other community members to contribute, then 🙂

**Comment by dingusagar** [comment]
Have created a PR for this issue here #306 . Please review and give comments if any.
