### ISSUE TITLE
Missing input channel on external action execution

### ISSUE THREAD

**Issue by scotbond** [RasaHQ/rasa-sdk#162]
**Rasa version**:
1.8.1
**Rasa SDK version**:
1.8.1
**Python version**:
3.7.7 on linux
**Issue**:
I am calling API endpoint `/conversations/{id}/trigger_intent`, to trigger an intent
which is set to trigger a specific `Action` via `domain.yml`.
It seems the `Tracker` object passed into the action is missing an input channel (see the actual API call below).
In the action's `run` function,`tracker.get_latest_input_channel()` returns `None`.
Everything else works fine during normal conversation flow. It happens only
on executing the action externally with `trigger_intent`. 

My setup:  
**domain.yml:**
```yml
...
- intent_myintent:
    triggers: action_myaction
...
```

**actions.py:**
```python

class ActionMyAction(Action):
    def name(self) -> Text:
        return 'action_myaction'

    def run(self, 
            dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[EventType]:

        channel = tracker.get_latest_input_channel()
        logging.debug(f'Input channel: {channel}')
        return []

```

API Call:
```
POST /conversations/{id}/trigger_intent?output_channel=telegram&token=<token>
BODY:
{
	"name": "intent_myintent"
}
```
Rasa API response status 200 OK

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by scotbond** [comment]
Any updates? :(

**Comment by degiz** [comment]
Hey @scotbond 

Sorry for the delayed answer!

The docstring of `Tracker::get_latest_input_channel` says: 
> Get the name of the input_channel of the latest UserUttered event

So it goes over the evens in reverse order trying to get the latest `UserUttered` event and get the channel name used.
As long as there was any utterance before you used `trigger_intent` endpoint, the result will not be `None`.

Do you experience this problem _after_ normal user utterance?
