### ISSUE TITLE
_sdk_loaded blocks registering of dynamically defined actions

### ISSUE THREAD

**Issue by MichaelMarien** [RasaHQ/rasa-sdk#204]
**Rasa version**:
1.9.5
**Rasa SDK version**:
1.10.0
**Python version**:
Python 3.7
**Operating system** (windows, osx, ...):
RHEL7

**Issue**:
We have a very specific situation in our action server and the introduction of the `_sdk_loaded` attribute breaks this. We have an easy work around, but still want to report this issue as reference.

**Error (including full traceback)**:
No error, but most of are actions are not registered.

**Command or request that led to error**:
`rasa run actions `

**Contents of actions.py**:
Minimal example
```
from rasa_sdk import Action

class Parent(Action):

    action_name = "parent"
    utter_list = None

    def name(self):
        return self.action_name

    async def run(self, dispatcher, tracker, domain):
        return []

Child = type("Child ", (Parent,), {"utter_list": ["utter_child"], "action_name": "child"})
```
Due to the dynamic introduction of the child class, it is no longer registered as it gets it `_sdk_loaded`  attribute from the parent after it's registered. Ideally, the parent would be abstract, but in our case it has no abstract methods. Worth to mention again that we are not blocked and have an easy fix but other users might run into issues with a similar root cause, so want to report it anyway.

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by federicotdn** [comment]
@MichaelMarien Thanks for reporting this, please check if `1.10.1` is working correctly for you when you can.

**Comment by federicotdn** [comment]
Fixed in https://github.com/RasaHQ/rasa-sdk/pull/212

**Comment by MichaelMarien** [comment]
> @MichaelMarien Thanks for reporting this, please check if `1.10.1` is working correctly for you when you can.

Works! thanks
