### ISSUE TITLE
Utilizing tracker in slot_mappings of form action

### ISSUE THREAD

**Issue by grumpygordon** [RasaHQ/rasa-sdk#216]
**Description of Problem**:

I've been implementing a form action which walks through decision tree, each time asking a question and expecting an answer of the form `yes` or `no`. I have only one slot called `node` which is the id of the current node. Each time I ask a question depending on `node` value and then I add 2 `from_intent` for `slot_mapping` function. The thing is that future value of `node` which I pass to `from_intent` function depends both on the answer and current `node` value, therefore I need to have a tracker in `slot_mapping` function.
This is a bit different from a default form action since I reuse same slot multiple times, but it looks like the best way of implementing decision tree using form action, since it can be easily generalized because each tree is represented by questions and edges, which is representable by json file.

**Overview of the Solution**:

Add `tracker` to `slot_mappings` function in `forms.py` file, as well as to `get_mappings_for_slot` function. 
**Examples** (if relevant):

**Blockers** (if relevant):

**Definition of Done**:

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @TyDunn will get back to you about it soon! ✨

**Comment by Ghostvv** [comment]
Did you try to train ML policy on the stories instead of implementing decision tree? The problem is that maintaining decision tree becomes quite hard.

But you can override these methods in your subclass of `FormAction` with different signature, I don't think there is a need to update superclass

**Comment by grumpygordon** [comment]
Maybe I'm inexperienced with stories, but how many of them do you expect to create for having a decision tree with 7 terminal nodes? And what if instead of a tree it is a directed acyclic graph? My method was implemented with intention of maintaining decision trees becoming relatively easy.

Also I did exactly what you suggested with overwriting sublclass methods, but for that I had to copy 4 methods and change just 1 line in each of them, which looks unneccesary since I don't see downsides of updating methods' signature.

**Comment by Ghostvv** [comment]
the story is directed acyclic graph. So it's kind of natural to use them. Up to you of course, bit the problem with decision tree raises when you need to expand it again and again

**Comment by Ghostvv** [comment]
in principle, I agree, since most of the methods take `tracker`, it makes sense to add it to `slot_mappings` as well

**Comment by grumpygordon** [comment]
That's the thing with my implementation, that it is very easy to expand/change existing tree and add new ones, because I define them as a list of edges with a text in each node, and after changing something I only need to restart action server instead of retraining model or smth like that. For an example, this is my decision tree definition for 16 nodes
```
self.dict = [
			['Is your file of Excel format?', {'affirm': 1, 'deny': 3}],
			['Do you have merged cells in your excel file?', {'affirm': 2, 'deny': 3}],
			['Please, remove any merged cells from your file and try again', 'action_listen'],
			['Have you imported all variables successfully?', {'affirm': 8, 'deny': 4}],
			['Is there any duplicated variable names in the file?', {'affirm': 5, 'deny': 6}],
			['In order to import the file, please rename variables, so that all of them have unique names.', 'action_listen'],
			['Is the structure of the first row correct?', {'affirm': 9, 'deny': 7}],
			['To import the file, please adhere to defined structure', 'action_listen'],
			['Have all of your data imported correctly?', {'affirm': 9, 'deny': 10}],
			['I understand. For your issue we have to create a ticket to fix it, it would be great if you can describe us your problem in more details.', 'mail_form'],
			['Do you have any dates in the document?', {'affirm': 11, 'deny': 12}],
			['To import the file, the dates of the document must be set up in this format: dd/mm/yyyy', 'action_listen'],
			['Do you have any decimal numbers in the file?', {'affirm': 13, 'deny': 14}],
			['To import the file, you have to use "." (dots) instead of "," (commas) as a decimal separator', 'action_listen'],
			['Do you have the same number of columns in each row?', {'affirm': 15, 'deny': 9}],
			['To be able to import the file, you have to make sure that all rows have the same number of columns(for csv you need the same amount of commas in each row)', 'action_listen']
		]
```

Obviously I tried to use stories to create a decision tree, but I found out that it looked very bad, also if I wanted to change something in the middle of a tree I would have to change all descedants of a node. And if I wanted to use DAG instead of a tree, I would have to create checkpoints, otherwise number of stories would be too much. For me it looked like quite a mess. Do I miss something in your idea, or is it what I described above? I would be very pleased to hear your advice on this idea.

**Comment by Ghostvv** [comment]
maybe, it's hard to say what is the best approach. But could you please create a PR to add `tracker` to the signatures

**Comment by wochinge** [comment]
@grumpygordon Interesting use case! I have a question regarding your implementation. How do you map a `node` to an action which the bot should execute? Or do you simple use the `dispatcher` to ask the user?

**Comment by grumpygordon** [comment]
For intermediate nodes I indeed utter required question, and in the terminal node I use `FollowupAction`

**Comment by wochinge** [comment]
Sounds good! We are currently doing a larger refactoring of the forms and wanted to make sure that uses cases such as yours would still be doable 👍

**Comment by grumpygordon** [comment]
Can you tell why and what are you doing with forms? I'm working with them very closely, and it might be a lot of work for me if you refactor it hugely :D

**Comment by wochinge** [comment]
Hi @grumpygordon ,

this is still in a prototype stage but we want to make it more intuitive to use fixed dialog rules with Rasa Open Source. Part of that is moving the current `FormAction` to the Rasa Open Source code base (this also makes it easier to implement a SDK in a different language since the `FormAction` logic is quite complex. Slot mappings and validate calls can still be implemented with custom actions so in your case it should be not a problem at all.

**Comment by grumpygordon** [comment]
I'm not quite sure, because I overwrote `FormAction` class to for example reask questions that user didn't answer. Also I don't really overwrite `validate` function, only `request_next_slot` and some others just because I need tracker in `slot_mappings` as described in the issue.

**Comment by wochinge** [comment]
Would it be possible to have a look at your implementation? Then I could check it myself.

**Comment by grumpygordon** [comment]
Sure, it would be nice if I can send it to you in DM, because it is used in company I'm currently working on.

**Comment by wochinge** [comment]
Sure, my mail is t.wochinger@rasa.com 👍 Thanks a lot for your support!

**Comment by grumpygordon** [comment]
Let me add some comments and add one feature before sending to you. It should take 1-2 days.
