### ISSUE TITLE
formaction should support sentence level "slots"

### ISSUE THREAD

**Issue by Chriszhangmw** [RasaHQ/rasa-sdk#219]
**Description of Problem**:
some clinic diagnosis support systems, our doctor defines three inputs, the first one is main complaints, the second sentence is current medical history, the last one is past medical history. when we create the form action, we can define required_slots to control if the user's inputs are satisfied by the system, if yes, form action will execute submit function. but for the above situation, the required inputs should sentence level instead of entity level.
even we can use tracker.latest_message['text'] to get the last input sentence, but it is not enough, my clinic diagnosis support systems should receive three sentences.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @akelad will get back to you about it soon! ✨

**Comment by akelad** [comment]
Hey @Chriszhangmw, could you give an example of a conversation and how you would expect the slots to be filled?

**Comment by Chriszhangmw** [comment]
thank you for your timely response.
My aim is to build a clinical diagnosis support system, the system request three inputs:
the first one is Chief complaint(sentence)
the second one is Current medical history(sentence)
the third one is Past medical history(sentence)
after all three parts are provided, then the clinical diagnosis support system will work.
obviously, this case is suitable for form action in rasa. 
if the first one is a symptom(entity)
and if the second one is medical(entity)
and if the third one is a disease(entity)
it is easy for rasa, I can define the slot and entity in my story and domain file, but for my case, the three parts are sentences instead of entities. you may suggest me to use tracker.latest_message[“text”] to get the sentence, but it only get the last one, I want to collect the three sentences.
wish you can understand my question and give me some hits if rasa can handle the situation. many thanks

**Comment by akelad** [comment]
So you can fill slots by using the `from_text` slot mapping in your forms. As far as I understand, your bot is asking three questions, and the user is providing three answers right?
I would say store those in 3 different slots, with the `from_text` slot mapping.
Does that answer your question?

I'm going to close this issue for now as it's more of a usage question, if you have further questions please post in our community [forum](https://forum.rasa.com)
