### ISSUE TITLE
Creating subclass of subclass of Action works incorrectly

### ISSUE THREAD

**Issue by grumpygordon** [RasaHQ/rasa-sdk#233]
**Rasa version**: 1.10

**Rasa SDK version**: 1.10

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux

**Issue**: Creating subclass `B` of subclass `A` of class `Action` would lead to registering of class `A`, but not registering class `B`, unless class `A` is abstract. This is because in `register_action` method of `ActionExecutor` class is getting tagged by setting attribute `_sdk_loaded`. The case is that it will be set in class `A`, and since `B` is subclass of `A`, `B` will be skipped since it already has this attribute.

**Error (including full traceback)**:
Class `A` registered, `B` is not
**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python
class A(Action):
    pass
class B(A):
    pass
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by lhr0909** [comment]
Running into the same issue when I am updating my code base to 1.10. After digging the source code of ActionExecutor, Seems like it moved to use [`abc`](https://docs.python.org/3/library/abc.html) for tagging abstract instead (it used to be done [by adding a `Meta` inner class with `abstract` flag](https://github.com/RasaHQ/rasa-sdk/issues/29#issuecomment-463959719)).

I have just made the following changes to my code and made it work.

```python
from abc import ABC, abstractmethod
class A(ABC, Action):
    # make sure to define abstract method using the annotation, this is how the ActionExecutor detects abstract methods
    @abstractmethod
    def some_abstract_method(self):
        pass
class B(A):
    pass
```
