### ISSUE TITLE
Not asking for slot again when validation fails

### ISSUE THREAD

**Issue by NielsRogge** [RasaHQ/rasa-sdk#240]
**Description of Problem**:
I encountered the same problem as in [this thread on the Forum](https://forum.rasa.com/t/mute-utter-ask-in-forms-for-validation-questions/9157). When using a form action, and a certain form validation fails (for example, the number of people in a restaurant reservation), the bot replies with something like this:

    number of people should be a positive integer, please try again
    how many people?

In other words, it both replies with the `utter_wrong_number_of_people` and `utter_ask_number_of_people` utterances. To me (and probably a lot of people), this is not logical, it should only reply with the `utter_wrong_number_of_people` utterance. It should not re-ask the slot again. However, currently, the [request_next_slot](https://github.com/RasaHQ/rasa-sdk/blob/e81674d80cdee56f149578af1e4b11cf3b5dfdfc/rasa_core_sdk/forms.py#L371) method will always `utter_ask_slot` regardless of the context, i.e. if it is the first time the user has been asked this, or if the form is asking it again because of clarification.

**Overview of the Solution**:
Providing us with the option of muting the `utter_ask` action when a validation fails.

Currently there's a workaround (as suggested in the forum), but this is quite cumbersome. 

This would be greatly appreciated!

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @rctatman will get back to you about it soon! ✨
