### ISSUE TITLE
Switch to mypy

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa-sdk#245]
**Problem:**
We repeatedly had code issues which could have code by type checks. We currently use `pytype` and it didn't find very simple things like the one which @m-vdb shared [here](https://gist.github.com/m-vdb/d24a45120cae0daa886f35e2aa032260) and could have prevented [this issue](https://github.com/RasaHQ/rasa-x/pull/3328).

**Proposed Solution**
`mypy` seems better suited and would have caught these issues. To gain more experience with it, we should start switching our smallest project, `rasa-sdk` to `mypy`. Depending on the results we can decide whether it's worth switching `rasa` or `rasa-`x, too.

**Steps**
- [ ] Switch `rasa-sdk` to `mypy`
- [ ] Make notes of all points of frictions / cool things during the process
- [ ] Compare the speed of the type checks (how much faster / slower is it than `pytype`

**Comment by nathan-chappell** [comment]
glad to hear you guys are switching to mypy.  I've been using it for awhile, and am looking forward to using it with rasa.

**Comment by m-vdb** [comment]
@nathan-chappell thanks for your feedback 🎉 `mypy` is now in use in `rasa`'s master (as of https://github.com/RasaHQ/rasa/pull/6470). Enjoy!
