### ISSUE TITLE
Changes in abstract Action detection starting in 1.10.0

### ISSUE THREAD

**Issue by govertbuijs** [RasaHQ/rasa-sdk#251]
**Rasa version**: 1.9.7

**Rasa SDK version**: 1.10.0

**Python version**: 3.7.5

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Starting with Rasa SDK version 1.10.0 the detection of abstract Action classes changed.
It used to be done via the 'abstract' property of the Meta-class of an Action class.
But this changed to inspect.isabstract() in executor.py (ActionExecutor._register_all_actions()), starting version 1.10.0 

Changing the (abstract) class to inherit from ABC fixed this, but i couldn't find any documentation for this.
(In Python 3.7.x it seems you need to have at least 1 abstract method in the class, 
otherwise inspect doesn't recognize the class as abstract).

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by adamwojt** [comment]
Let's reopen this. Quite important feature.
