### ISSUE TITLE
tracker.get_last_event_for ignores restart events

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#280]
**Rasa version**: 1.9.5

**Rasa SDK version**: 1.9.0 (same issue with master)

**Python version**: 3.7

**Operating system** (windows, osx, ...): Unix

**Issue**:
When calling `tracker.get_last_event_for("user", skip=n)`, events that are before a `restart` event are included. 

This seems to be due to an issue in the `applied_events`. 

``` 
if event.get("name") == "restart":
    applied_events = []
elif event.get("name") == "undo":
    undo_till_previous("action", applied_events)
elif event.get("name") == "rewind":
    ...
```
From the code above, the event `name` is `None`. I believe it should get the `event` as `event.get("event")` instead. 

**Command or request that led to error**:
```
# run an action with a `Restarted()` event
# in another action, run:
tracker.get_last_event_for("user", skip=n)
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@nbeuchat Thanks for raising this issue. You seem to be right. Would you be up for fixing this issue and submitting a PR?

**Comment by tabergma** [comment]
Yes, master would be great. Thanks :rocket:
