### ISSUE TITLE
ModuleNotFoundError: No module named 'actions.utils.tests.knowledge_base' within docker container when __init__.py in actions/utils/tests/ is present

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#298]
**Rasa version**: 1.9.7

**Rasa SDK version**: 1.9.0

**Python version**: 3.6.10

**Operating system** (windows, osx, ...): Ubuntu (within Docker container)

**Issue**:
When starting the rasa sdk in a docker container, I get a `ModuleNotFoundError: No module named 'actions.utils.tests.knowledge_base'`. The thing is that I do not have any `tests.knowledge_base` anywhere in my code. 

When I remove the `__init__.py` file from my `actions/utils/tests` folder, it works fine. This is very confusing as it only fails within the docker container. 

It's not a very big deal as I can just remove this file but would be great to understand what is going on. 

**Error (including full traceback)**:
```
action_server_1  | 2020-10-08 10:48:10 ERROR    rasa_sdk.executor  - Failed to register package 'actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_sdk/executor.py", line 208, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_sdk/executor.py", line 202, in _import_submodules
action_server_1  |     self._import_submodules(full_name)
action_server_1  |   File "/app/rasa_sdk/executor.py", line 200, in _import_submodules
action_server_1  |     results[full_name] = importlib.import_module(full_name)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
action_server_1  | ModuleNotFoundError: No module named 'actions.utils.tests.knowledge_base'
chatbot_action_server_1 exited with code 1
```

**Command or request that led to error**:
```
docker-compose up 
# which runs `python -m rasa_sdk --actions actions`
```

**Contents of actions** (if  relevant):
Folder with the following structure (removed irrelevant ones)
```
actions
├── clients.py
├── constants.py
├── forms
│   ├── form_contact.py
│   ├──...
│   ├── __init__.py
├── __init__.py
├── utils
│   ├── formatting.py
│   ├── ...
│   ├── __init__.py
│   ├── tests
│   │   ├── test_formatting.py
│   │   ├── ....py
│   │   ├── __init__.py  [ISSUE WHEN IT'S HERE]
└── ...
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
