### ISSUE TITLE
Problem with _query_attribute method in class ActionQueryKnowledgeBase

### ISSUE THREAD

**Issue by williamwongys** [RasaHQ/rasa-sdk#311]
```
object_name = get_object_name(
            tracker,
            self.knowledge_base.ordinal_mention_mapping,
            self.use_last_object_mention,
        )

if not object_name or not attribute:
            dispatcher.utter_message(template="utter_ask_rephrase")
            return [SlotSet(SLOT_MENTION, None)]
```
When object_name==0, which happens when id is 0, it will execute utter_ask_rephrase which is not correct.

To work around this problem, I have to avoid using 0 for id in defining knowledgebase.
Is this a bug?  I saw your example in https://rasa.com/docs/action-server/knowledge-bases/
```
    "restaurant": [
        {
            "id": 0,
            "name": "Donath",
            "cuisine": "Italian",
            "outside-seating": true,
            "price-range": "mid-range"
        },
```
id 0 should be supported.

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
Ah, I see the problem. I guess in most cases `object_name` refers to an actual name, e.g. string, so this is not a problem. But if it is actual pointing to the id itself and the value is 0 or 1, it is interpreted as a boolean value. So the check fails in case of 0.

Thanks for catching this! Do you want to submit a fix for this?
