### ISSUE TITLE
Nicely deal with repeated slot validation failures in forms

### ISSUE THREAD

**Issue by ArjaanBuijk** [RasaHQ/rasa-sdk#317]
**Description of Problem**:
When a user is not providing the correct value for a requested slot, the form goes into an infinite loop re-asking for that slot. After N validation failures, the form should provide a better explanation of the requested slot, and then ask the user if they want to continue or not.

**Overview of the Solution**:
- Add a global parameter defining how many repeated slot validation failures are allowed. Configurable by user.
- Allow user to define an `explain_{slot}` method, similar to the `validate_{slot}` method.

Everything else should work out-of-the-box.

**Examples** (if relevant):
A demonstrator implementation using current capabilities was implemented as a custom action in financial-demo for rasa 2.0, currently maintained in the [rasa-2-0 branch](https://github.com/RasaHQ/financial-demo/tree/rasa-2-0)

**Comment by akelad** [comment]
we decided this should be implemented in the Rasa Open Source code directly. @ArjaanBuijk can you link to the specific code snippet in the fin demo repo?

**Comment by wochinge** [comment]
In case we implement this within Rasa Open Source we need a way to configure the default `FormAction`. This again should probably be a separate task.

**Comment by kaustuk** [comment]
Hi @akelad @wochinge is someone working on this feature? If not I would like to work on it

**Comment by kaustuk** [comment]
Also this is very good feature to have for forms. Since mostly people what too exit loop in form/different utterance if it has reached till certain retires.

**Comment by kaustuk** [comment]
> Hi @akelad @wochinge is someone working on this feature? If not, I would like to work on it

@wochinge @akelad any update? I can create this as feature request also in Rasa Open Source(if required) Since form has been move to Rasa Open Source

**Comment by wochinge** [comment]
@ArjaanBuijk are you working on it?

**Comment by ArjaanBuijk** [comment]
@kaustuk , @wochinge ,

A logic was implemented in the financial-demo, currently available in the `rasa-2-0` branch:
https://github.com/RasaHQ/financial-demo/tree/rasa-2-0

The logic is a customization of the `FormValidationAction`, and can be found here:
https://github.com/RasaHQ/financial-demo/blob/rasa-2-0/actions/custom_forms.py 

I think it would be great to generalize this logic and implement it as a standard feature of the forms in Rasa, and updating the regular FormValidationAction in rasa-sdk.

**Comment by wochinge** [comment]
@kaustuk I think we can keep this issue. I added to our squad's board.

**Comment by akelad** [comment]
@wochinge still relevant?

**Comment by wochinge** [comment]
yep

**Comment by kaustuk** [comment]
Hi @wochinge, sorry I was a bit busy past couple of months so couldn't look into this issue. Since this is still relevant I would like to submit PR for this. I am planning to come up with a list of changes by this weekend. Hope that works, right?

**Comment by wochinge** [comment]
@kaustuk As we're working towards Rasa Open Source 3.0 which includes (another) revamp of forms I'd probably hold off with this change a bit. What do you think @ancalita ?

**Comment by kaustuk** [comment]
@wochinge thanks for the reply. Yeah, that makes sense to watch for Rasa 3.0

**Comment by kshitij-g** [comment]
Hi, is there any update on this feature?

**Comment by vapdev** [comment]
Hey any update

**Comment by m-vdb** [comment]
:bulb: **Heads up! We're moving issues to Jira**: https://rasa-open-source.atlassian.net/browse/OSS.

From now on, this Jira board is the place where you can browse (without an account) and create issues (you'll need a free Jira account for that). This GitHub issue has been manually migrated to: https://rasa-open-source.atlassian.net/browse/OSS-667. Do not forget to subscribe to it!

:arrow_right: More information in the forum: https://forum.rasa.com/t/migration-of-rasa-oss-issues-to-jira/56569.

Closing this issue as a result 😄
