### ISSUE TITLE
Direct Knowledgebase Questions Dispatching Full Objects

### ISSUE THREAD

**Issue by abdullahnaseem** [RasaHQ/rasa-sdk#334]
https://github.com/RasaHQ/rasa-sdk/blob/197af3346c63fc39ec5ce2a268dee69c86d320b1/rasa_sdk/knowledge_base/actions.py#L73

I am using the default **knowledgebasebot** template from `action_query_knowledge_base`  example and running into an issue

I have trained the bot with the following example and found that the **NLU** detects the correct **Entities** and **Intents** but the action returns the full list of objects instead of returning the specific attribute.

**nly.yml**

`- does [Hilton]{"entity": "hotel"} [hotel]{"entity": "object_type", "value": "hotel"} have free [wifi]{"entity": "attribute", "value": "free-wifi"}?`

**input text**

`does Hilton hotel have free wifi`

**rasa interactive**

`Is the intent 'query_knowledge_base' correct for 'does [Hilton](hotel) [hotel](object_type) have free [wifi]{"entity": "attribute", "value": "free-wifi"}' and are all entities labeled correctly?`

**response**

`Found the following objects of type 'hotel':
      1: Berlin Wall Hostel | (Berlin)
      2: Hilton | (Frankfurt am Main)
      3: Berlin Hotel | (Berlin)
      4: Jugendherberge | (Berlin)
      5: City Hotel | (Frankfurt am Main)`

Is there something I am missing?
The same thing seems to work when I ask `list of hotels` first and then ask for the specific hotel and attribute even if the hotel is not in the list.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @Ghostvv will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
That is expected due to the way it is implemented. The bot always first needs a generic question to know what kind of object you are interest in. Just after that the bot will be able to handle specific questions to one particular object, e.g. hotel.
If you want to change this behaviour you could modify the knowledge base action, see https://rasa.com/docs/action-server/knowledge-bases

**Comment by abdullahnaseem** [comment]
So you are saying that to do something like that I will have to first ask the bot about (hotel)[object type] like I tried and that's the way its supposed to work?

**Comment by tabergma** [comment]
Yes, as you mentioned here
> The same thing seems to work when I ask list of hotels first and then ask for the specific hotel and attribute even if the hotel is not in the list.

**Comment by abdullahnaseem** [comment]
Ok, thanks for the clarification.
