### ISSUE TITLE
wrong value for `object_name` argument of `rasa_sdk.knowledge_base.actions.ActionQueryKnowledgeBase.utter_attribute_value()`

### ISSUE THREAD

**Issue by howl-anderson** [RasaHQ/rasa-sdk#365]
**Rasa SDK version**: 2.2.0a1

**Operating system** (windows, osx, ...): Ubuntu 18.04.5 LTS

**Issue**:

`rasa_sdk.knowledge_base.actions.ActionQueryKnowledgeBase.utter_attribute_value()` expects argument `object_name` to be `Text` type (from code and typing hint).

But actually, there is a bug that causes the value to be a lambda function.

I will submit a PR later to fix this.

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Thanks for your consistent contributions @howl-anderson 🙏

**Comment by koernerfelicia** [comment]
Closed by https://github.com/RasaHQ/rasa-sdk/pull/407
