### ISSUE TITLE
Action execution is never rejected in a form when required_slots method is set 

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa-sdk#370]
**Rasa version**: 2.1.1

**Rasa SDK version**: 2.1.1

**Python version**: 3.7.9

**Operating system**: Ubuntu

**Issue**:
I have a form `form_preferences`. In my action server, I have a `FormValidationAction` named `validate_form_preferences` which sets the `required_slots` function so that a few slots can be added only if others have a certain value. 

The problem is that when this `required_slots` function is set, the form is never rejected and it is therefore impossible to get out of the form with stories/rules. It just asks the form questions over and over even if nothing is extracted/validated. 

For example, I have a rule like this (to explain what the question is about):

```
- rule: Explain within form preferences
  condition:
  - active_loop: form_preferences
  steps:
  - intent: explain
  - action: action_explain
  - action: form_preferences
```

When the intent is `explain` is detected, the rule policy simply predicts `form_preferences` again without triggering the `action_explain`. 

![image](https://user-images.githubusercontent.com/8236283/101641811-80495f00-3a32-11eb-9d2b-bd39c949edc4.png)

If I comment out the `requested_slot` function, restart my action server, and ask again, it works fine (it's changing question in the form preferences because I was defining that in my function, but the action execution is correct):

![image](https://user-images.githubusercontent.com/8236283/101641877-97884c80-3a32-11eb-9549-92512b65c589.png)

**Story (JSON) when failing**:
This is the story when the action is not predicted correctly. 
```
{
    "event": "action",
    "timestamp": 1607522374.9666876793,
    "name": "form_preferences",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "slot",
    "timestamp": 1607522374.9668533802,
    "name": "requested_slot",
    "value": "preferences_target_price"
},
{
    "event": "bot",
    "timestamp": 1607522374.9668636322,
    "metadata": {
        "template_name": "utter_ask_preferences_target_price"
    },
    "text": "What is your target budget?",
    ...
},
{
    "event": "action",
    "timestamp": 1607522375.4643621445,
    "name": "action_listen",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "user",
    "timestamp": 1607522485.3801364899,
    "text": "why do you need that?",
    "parse_data": {
        "intent": {
            "id": -6312993079781975994,
            "name": "explain",
            "confidence": 0.9466386437
        },
        "entities": [],
        "text": "why do you need that?",
        ...
    },
    "input_channel": "facebook",
    "message_id": "61968899fc534590b443e120a13cf52c",
    "metadata": {}
},
{
    "event": "action",
    "timestamp": 1607522486.8808698654,
    "name": "form_preferences",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "slot",
    "timestamp": 1607522486.8810045719,
    "name": "requested_slot",
    "value": "preferences_target_price"
},
```

**Story (JSON) when it works fine**:
This is the story when the input is correctly rejected and the `action_explain` predicted. -> `requested_slots` method is commented out. 
```
{
    "event": "action",
    "timestamp": 1607523337.4427978992,
    "name": "form_preferences",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "slot",
    "timestamp": 1607523337.4431116581,
    "name": "requested_slot",
    "value": "preferences_target_price"
},
{
    "event": "bot",
    "timestamp": 1607523337.4431276321,
    "metadata": {
        "template_name": "utter_ask_preferences_target_price"
    },
    "text": "What is your target budget?
},
{
    "event": "action",
    "timestamp": 1607523337.8496460915,
    "name": "action_listen",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "user",
    "timestamp": 1607523429.8035414219,
    "text": "why do you need that?",
    "parse_data": {
        "intent": {
            "id": -6312993079781975994,
            "name": "explain",
            "confidence": 0.9466386437
        },
        "entities": [],
        "text": "why do you need that?",
        ...
        }
    },
    "input_channel": "facebook",
    "message_id": "2857cdf109bc4406a06c4b413e339c5f",
    "metadata": {}
},
{
    "event": "action_execution_rejected",
    "timestamp": 1607523433.3903949261,
    "name": "form_preferences",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "action",
    "timestamp": 1607523433.9477674961,
    "name": "action_explain",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "bot",
    "timestamp": 1607523433.9479513168,
    "metadata": {...},
    "text": "We need this information to prepare a viewing request.", 
    ...
},
{
    "event": "action",
    "timestamp": 1607523435.5147461891,
    "name": "form_preferences",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
},
{
    "event": "slot",
    "timestamp": 1607523435.514806509,
    "name": "requested_slot",
    "value": "has_pet_type"
},
{
    "event": "bot",
    "timestamp": 1607523435.5148096085,
    "metadata": {
        "template_name": "utter_ask_has_pet_type"
    },
    "text": "What kind of pet do you have?",
    ...
},
{
    "event": "action",
    "timestamp": 1607523435.9542570114,
    "name": "action_listen",
    "policy": "policy_1_RulePolicy",
    "confidence": 1.0
}
```

**Comment by nbeuchat** [comment]
Maybe @wochinge or @ArjaanBuijk can help here as it seems you had worked on the requested slots feature? 🙏🏻

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @JustinaPetr will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by nbeuchat** [comment]
@JustinaPetr do you know what could be going on or if I'm doing anything wrong? We currently can't finish our migration to Rasa 2.x because of this issue. Thanks for your help 🙏🏻

**Comment by nbeuchat** [comment]
I'd be more than happy to open a PR for it if I get a few pointers. Any recommendation on where/how to get started?

**Comment by wochinge** [comment]
@nbeuchat Sorry for the late answer - we are currently working hard to get out Rasa Open Source 2.2. I think [this](https://github.com/RasaHQ/rasa/pull/7564) fixes your issue. I'll try to test this tomorrow and then either ship it with 2.2 or ship it as patch 👍🏻

**Comment by nbeuchat** [comment]
Hi @wochinge! Thanks so much for looking into it (and sorry for pinging on every channel I know 🙈). Looking forward to 2.2 🙂

**Comment by wochinge** [comment]
closed by https://github.com/RasaHQ/rasa/pull/7564
