### ISSUE TITLE
Bad page preview

### ISSUE THREAD

**Issue by en-ashay** [RasaHQ/rasa-sdk#372]
https://rasa.com/docs/action-server/http-api-spec

Page shrinks on opening in chrome and firefox browsers. ( didn't try for others)

![rasadocissue](https://user-images.githubusercontent.com/30903814/102009298-8904a280-3d5c-11eb-8408-6c47210abf98.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
@lunelson do you know why this happens?

**Comment by lunelson** [comment]
@tmbo this is a configuration which isn't supported. [This MDX page](https://github.com/RasaHQ/rasa-sdk/blob/master/docs/docs/api-spec.mdx) should be deleted; the correct URL for the API spec is this:

https://rasa.com/docs/action-server/pages/action-server-api
