### ISSUE TITLE
Missing tag 2.1.3

### ISSUE THREAD

**Issue by staticdev** [RasaHQ/rasa-sdk#375]
**Rasa version**: 2.1.3

**Rasa SDK version**: ?

**Python version**: 3.8

**Operating system** (windows, osx, ...): Ubuntu/Debian

**Issue**: I usually pair main requirements to work with the same version of rasa and rasa-sdk. Rasa is on version 2.1.2 and Rasa-sdk jumped to 2.2.0 and only have 2.1.2. Also [documentation](https://github.com/RasaHQ/rasa-sdk/blob/master/README.md) does not say anything about compatibility for Rasa 2.0+. 

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
