### ISSUE TITLE
Typos in Documentation

### ISSUE THREAD

**Issue by zyberg2091** [RasaHQ/rasa-sdk#379]
This issue was raised in RasaHQ/rasa as #7627.I am recreating this issue here to send the PR to remove the typos in sdk-dispatcher documentation.

![Annotation 2020-12-23 232519](https://user-images.githubusercontent.com/42847318/103024685-58034980-4576-11eb-8565-11894135792b.png)

Two issues were raised in the the buttons parameter of the dispatcher's utter_message method .First one is the message is wrongly spelled as messsage and second is that the closing bracket is missing in the utter_message method.

link : https://rasa.com/docs/action-server/sdk-dispatcher

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @koaning will get back to you about it soon! ✨

**Comment by melindaloubser1** [comment]
Hi @zyberg2091 thanks for reporting, will be closed by https://github.com/RasaHQ/rasa-sdk/pull/381
