### ISSUE TITLE
Attach headers to domain for OpenTracing / OpenTelemetry

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa-sdk#382]
**Description of Problem**:
The w3c [Trace Context](https://www.w3.org/TR/trace-context/) provides for passing tracing information via html headers. This is useful to inject OpenTrace and OpenTelemetry spans into headers to trace transactions across processes.

The SDK should support a method access the headers.

**Overview of the Solution**:
Attach the headers as another object on the existing Domain object.

**Definition of Done**:
- [ ] Tests are added
- [x] Feature is documented

**Comment by wochinge** [comment]
@rgstephens What are the alternatives to HTML headers? And has there been a discussion / decision whether OpenTracing / OpenTelemetry will be implemented within the Rasa products?

**Comment by rgstephens** [comment]
I haven't looked at alternatives. The tracing info would need to be part of the http request. Why would we want to do this different from the W3C standard?

@scottruitt and I discussed this recently and this has been discussed with several customers. Also see Rasa issue [#7196](https://github.com/RasaHQ/rasa/issues/7196).

**Comment by wochinge** [comment]
@rgstephens I think I was confuse by the `HTML` headers - you meant `HTTP`, right?

**Comment by rgstephens** [comment]
Yes, should have said http.

**Comment by JustinDroege** [comment]
Is there any progress?
