### ISSUE TITLE
Windows testing for rasa-sdk

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa-sdk#405]
**Description of Problem**:

`rasa` runs tests on Windows and Linux while `rasa-sdk` runs tests only on Linux. This might lead to problems like some `rasa-sdk` dependencies being not available on Windows (for example: https://github.com/RasaHQ/rasa-sdk/pull/404)

**Overview of the solution**:
Run `rasa-sdk` tests on Windows as well

**Definition of Done**:
- [x] Tests are added

**Comment by tczekajlo** [comment]
@alwx (cc @TyDunn @m-vdb) How is the issue related to the infra?

**Comment by m-vdb** [comment]
I think we can close this one for now
