### ISSUE TITLE
ActionQueryKnowledgeBase: utter_attribute_value wrong function argument

### ISSUE THREAD

**Issue by emanuel-metzenthin** [RasaHQ/rasa-sdk#406]
**Rasa version**: 2.2.5

**Rasa SDK version**: 2.2.0

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): osx

**Issue**: When using action_query_knowledge_base attributes are not uttered correctly as instead of the `object_name` the representation function of that object is passed to `utter_attribute_value` (here: https://github.com/RasaHQ/rasa-sdk/blob/f8c2ce00ca782835616c046a721d3eabf7aa816d/rasa_sdk/knowledge_base/actions.py#L248)

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Contents of actions.py** (if  relevant):
```python

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
thank you for spotting this! I was able to reproduce it. 

1. go to `examples/knowledgebasebot`
2. train a model and start `rasa shell`
3. say 'hotels' and then say 'does the last one offer breakfast?' 

bot responds with:
```
Your input ->  does the last one offer breakfast?                                                                                              
'<function ActionMyKB.__init__.<locals>.<lambda> at 0x7fb23b7fddd0>' has the value 'True' for attribute 'breakfast-included'.
```

@kedz since this was a place we thought about doing some more sophisticated NLG, maybe you want to jump on this one?
