### ISSUE TITLE
Drop support for Python 3.6

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa-sdk#501]
**Description of Problem**:
Python 3.6 end of life is [Dec 23rd 2021](https://endoflife.date/python). Our next major release could be an opportunity to drop support

**Definition of Done**:
- [ ] CI workflows are updated
- [ ] Documentation is updated
- [ ] Internal documentation is updated
- [ ] sanic is updated to v21.6.0
- [ ] branch / tag is created to be used for sanic update in rasa oss

**Comment by rodrigovssp** [comment]
#up

Em seg., 16 de ago. de 2021 05:09, Thomas Werkmeister <
***@***.***> escreveu:
