### ISSUE TITLE
tracker.get_intent_of_latest_message() method doesn't return intent from custom component

### ISSUE THREAD

**Issue by PaulPidou** [RasaHQ/rasa-sdk#548]
**Rasa version**:
2.8.6
**Rasa SDK version**:
2.8.2
**Python version**:
3.8.10
**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
The method `tracker.get_intent_of_latest_message()` doesn't return the intent from custom component but the first intent from intent_ranking instead.

This issue is due to this [line](https://github.com/RasaHQ/rasa-sdk/blob/5c4c0d756c1b0e368cf6efc2cf26ae5f176f8682/rasa_sdk/interfaces.py#L296)
I guess it should be replaced by `latest_message.get("intent").get("name")`.

I set the intent within my custom component in the following way:
```
confidence = 0.0 if intent_name is None else 1.0
intent = {"name": intent_name, "confidence": confidence}

if intent_name is not None:
    message.set(INTENT, intent, add_to_output=True)
```
(Following this [code](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/classifiers/_keyword_intent_classifier.py#L109))

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
