### ISSUE TITLE
endpoint for listing all loaded actions

### ISSUE THREAD

**Issue by jackfreed** [RasaHQ/rasa-sdk#60]
the action server is starting up with a list of available actions:

INFO     rasa_core_sdk.executor  - Registered function for 'action_joke'.

it would be nice to get a list of loaded actions during runtime e.g.

GET /actions

['action_joke']

**Comment by akelad** [comment]
@jackfreed can I ask what you would use this for?

**Comment by jackfreed** [comment]
we wanted to use it for auto creating the domain.yml file and make sure the actions are properly loaded and thus available.
