### ISSUE TITLE
support all message types in sdk (quick replies) 

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa-sdk#83]
alternatively we could deprecate support for quick replies and only keep the very general stuff supported in templates, with channel-specifc (e.g. quick replies) stuff delegated to custom json payloads.

**Comment by cowjen01** [comment]
@erohmensing @wochinge Hello, we are currently replacing all deprecated utter methods and custom json payloads by `utter_message` across our projects so they could be easily tested with Rasa Shell. But we really miss an option to send both buttons and quick replies via `utter_message` method. Quick replies are now supported across all channels and they can even be send from `domain.yml` templates. I suggest to add `quick_replies` argument to the method's [constructor](https://github.com/RasaHQ/rasa-sdk/blob/5cbb280d90d533fe8db069bca113e0f16849268c/rasa_sdk/executor.py#L27) so the SDK will not be only limitation to fully use all components via Rasa Shell utility.

**Comment by cowjen01** [comment]
@erohmensing Any updates about this issue? We would like to start working on it once we get a permission.

**Comment by erohmensing** [comment]
@cowjen01 that would be great! Let me know if you need any help with it.

**Comment by wochinge** [comment]
How is it going with the issue @cowjen01 ?

**Comment by erohmensing** [comment]
Unfortunately I think this issue should be closed, as we should move ahead with deprecating these: https://github.com/RasaHQ/rasa/issues/5239

**Comment by cowjen01** [comment]
@erohmensing I agree on this! We've stoped working on this issue due to https://github.com/RasaHQ/rasa/issues/5239. Sorry I didn't let u know guys. My apologies!
