### ISSUE TITLE
Can not Registered function for both of 'Action' and 'FormAction'

### ISSUE THREAD

**Issue by baphuc1998** [RasaHQ/rasa-sdk#91]
**Rasa SDK version**: 1.1.0

**Python version**:  3.7.3

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I can not register function for both of 'Action' and 'FormAction' at the same time.
When i use 'python -m rasa_core_sdk.endpoint --actions actions'. It's only register for Action. Otherwise,when use 'rasa run actions'. It's only register for FormAction.
How can I use both of them at the same time.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by letanloc1998** [comment]
I have the same problem

**Comment by letanloc1998** [comment]
You can fix
from rasa_sdk.forms import FormAction
from rasa_sdk import Action

**Comment by akelad** [comment]
yeah that's the correct syntax, don't think this is a bug
