### ISSUE TITLE
Pass valdate function in FormAction

### ISSUE THREAD

**Issue by letanloc1998** [RasaHQ/rasa-sdk#92]
**Rasa SDK version**:  1.1.0

**Python version**:  3.6.8

**Operating system** (windows, osx, ...): Ubuntu 18.04 LTS

**Issue**: I can't pass validate function in FormAction

class action_form_name(FormAction):
    def name(self) -> Text:
        return "action_form_name"

    def validate(self, dispatcher, tracker, domain):

        if 'intent_name' == tracker.latest_message['intent']['name']:
            #I want to pass here, don't do anything
            return []
        if tracker.get_slot('slot_nane') is None:
            dispatcher.utter_template("utter_name", tracker)
        return []
Does someone help me. Thank you.

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by erohmensing** [comment]
Please ask usage questions on our [forum](http://forum.rasa.com).
