### ISSUE TITLE
Compatibility issue with rasa 1.2.2

### ISSUE THREAD

**Issue by Lahirupc** [RasaHQ/rasa-sdk#97]
**Rasa SDK version**: 1.1.1

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu 18

**Issue**: Not compatible with rasa 1.2.2

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by erohmensing** [comment]
Thanks for pointing this out! I have a PR open to merge sdk 1.2.0 for compatibility, so this error should not show up anymore. However you should be able to safely ignore it for now :)
